### ISSUE TITLE
what should be the directory structure of the images?

### ISSUE THREAD

**Issue by muthiyanbhushan** [vonclites/squeezenet#5]
Hello,

For running this network what should be the directory structure for train, val and test folders.
Is it same as what Imagenet has.

Viz

train
    |--- folder_1- class#1
    |--- folder_2- class#2 
test 
   |--- 15000 images in test folder
val
   |--- 50000 images in val folder

Please, let me know.

Thanks.

**Comment by vonclites** [comment]
The input is TFRecords, not the raw images.  The format format for each example in the TFRecord is given by:
https://github.com/vonclites/squeezenet/blob/4b28bc2c7b064eacb14c209dbfcd3d0201f58635/inputs.py#L168

**Comment by muthiyanbhushan** [comment]
Hello @vonclites,

Can you please direct me to any tutorial which will convert raw images to tfRecords ?

Thanks.

**Comment by muthiyanbhushan** [comment]
I followed this tutorial and I was able to successfully generate tfrecords file for flower dataset.

https://kwotsin.github.io/tech/2017/01/29/tfrecords.html

Thank you.

**Comment by vonclites** [comment]
Cool.
